# Generated by Django 4.1.1 on 2022-10-13 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('foundation_date', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='player',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('riot', models.CharField(max_length=50, unique=True)),
                ('primary_rol', models.CharField(max_length=50)),
                ('horarios', models.CharField(choices=[('AF', 'Afternoon'), ('MO', 'Morning')], default='MO', max_length=2)),
                ('experience', models.CharField(max_length=300)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VLR_APP.team')),
            ],
        ),
        migrations.CreateModel(
            name='directivo',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('CEO', 'Ceo'), ('MANAGER', 'Manager')], default='CEO', max_length=7)),
                ('experience', models.CharField(blank=True, max_length=300)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLR_APP.team')),
            ],
        ),
        migrations.CreateModel(
            name='coache',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.CharField(max_length=300)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VLR_APP.team')),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnac', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
                ('directivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLR_APP.directivo')),
            ],
        ),
    ]
