# Generated by Django 4.1.1 on 2022-10-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VLR_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coache',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VLR_APP.team'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='VLR_APP.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VLR_APP.team'),
        ),
    ]
