# Generated by Django 4.1.1 on 2022-11-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLR_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
