# Generated by Django 4.1.1 on 2022-10-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLR_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='founder',
        ),
    ]
