# Generated by Django 4.1.3 on 2023-01-07 23:09

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('VLR_APP', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
