# Generated by Django 4.1.3 on 2023-01-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VLR_APP', '0002_auto_20230107_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VLR_APP.team'),
        ),
    ]
